name = "hyperSIS"
version = "1.0"
license = "LGPL-3.0-or-later"
author = "Wesley Cota"
maintainer = "wlcota@gmail.com"
copyright = "Copyright 2025, Wesley Cota"
[build]
auto-executables = true
auto-tests = false
auto-examples = true
module-naming = false
[install]
library = true
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
[dependencies]
stdlib = "*"
datastructs-fortran = {git="https://github.com/wcota/datastructs-fortran", tag="v0.3.8"}
rndgen-fortran = {git="https://github.com/wcota/rndgen-fortran", tag="v1.0.5"}
FLAP = {git="https://github.com/szaghi/FLAP"}
PENF = {git="https://github.com/szaghi/PENF"}
