network_import – HyperSIS
network_import Subroutine
15 statements
Source File
public subroutine network_import(net, filename, skip_check_consistency)
Arguments
Type Intent Optional Attributes Name
class(network_t), intent(inout) :: net
character(len=*), intent(in) :: filename
logical, optional :: skip_check_consistency
Calls
Called by
Call graph
network_import calls nodes, build_nodes_from_edges, check_topology_consistency, count_integers_from_string
read_network calls network_import