from pathlib import Path
from typing import Tuple
import numpy as np

def process_results(directory: str) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """
    Reads output files generated by the Fortran binary
    and returns numpy arrays.

    Adapt this to match the actual output format.
    """
    data_file = Path(directory) / "_results.dat"
    data = np.loadtxt(data_file)

    times = data[:, 0]
    rho_mean = data[:, 1]
    rho_var = data[:, 2]
    n_samples = data[:, 3]

    return times, rho_mean, rho_var, n_samples
